name: Reusable workflow example
on:
  workflow_call:
    inputs:
      username:
        required: true
        description: "test"
        
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
      #- uses: ./.github/actions/action1
        run: echo ${{ inputs.username }}
        shell: bash