name: Continuous Delivery - Development

on:
  push:
    branches:
      - dev
      - staging

jobs:
  continuous-delivery-development:
    name: Continuous Delivery - Development
    if: GITHUB_REF_NAME == 'dev'
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator

  cd-staging: 
    name: Staging (Lighter) CD
    if: GITHUB_REF_NAME == 'staging'
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::red'
        id: random-color-generator