name: Build and deploy
on: push

env:
  FILE: arch.txt
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build_step
        run: echo "Build ID= $BUILD_ID" > $FILE
        run: cat $FILE2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v2
      - run: cat $FILE
#      - run: echo ${{ needs.build.outputs.build_id }}
#  debug:
#    needs: [build, deploy]
#    runs-on: ubuntu-latest
#    if: ${{ failure() }}
#    steps:
#      - uses: actions/checkout@v2
#      - run: ./debug
