name: Continuous Delivery - Development

on:
  push:
    branches:
      - dev
      - stg

jobs:
  continuous-delivery-development:
    name: CD - Dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set selected color
        run: |
          echo '::set-output name=SELECTED_COLOR::green'
          echo $GITHUB_REF_NAME
        id: random-color-generator

  cd-staging: 
    name: CD - Stg
    #if: github.ref == 'refs/heads/stg'
    if: ${{ env.GITHUB_REF_NAME }} == 'stg'
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set selected color
        run: |
          echo '::set-output name=SELECTED_COLOR::red'
          echo $GITHUB_REF_NAME
        id: random-color-generator