name: Continuous Delivery - Development

on:
  push:
    branches:
      - dev
      - stg

jobs:
  continuous-delivery-development:
    name: CD - Dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set selected color
        run: |
          echo '::set-output name=SELECTED_COLOR::green'
          echo $GITHUB_REF_NAME
          echo "Current branch is:" $GITHUB_REF_NAME
        id: random-color-generator

  cd-staging: 
    name: CD - Stg
    if: github.ref == 'refs/heads/stga'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set selected color
        run: |
          echo '::set-output name=SELECTED_COLOR::red'
          echo $GITHUB_REF_NAME
          echo "Current branch is:" $GITHUB_REF_NAME
        id: random-color-generator

  run-local-action:
    name: "Run local action"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        # Checkout the repository first
        # Otherwise the workflow won't be able to find the action
      - uses: actions/checkout@v2

      - name: Run custom action
        # Use the location in the repository (without action.yml)
        uses: ./.github/actions/action1
        with:
          branchname: ${{ GITHUB_REF_NAME }}